Adding a section to the README on releases and where updates happen
rancher/wrangler pull request #274
Opened 2023-02-22 17:55 UTC by mattfarina

2023-02-22 19:54 UTC, cbron commented on README.md
> +
We need a comment that describes what the purpose of master is, otherwise devs will see that 1.1 is 2.7 and only merge to release/v1.1.

2023-02-23 00:46 UTC, rmweir requested changes
After addressing @cbron feedback, LGTM. Basically stating something like: devs should always merge into master and then the Wrangler versions in the table will be managed using the commits in master.

2023-02-23 16:40 UTC, mattfarina commented
@cbron @rmweir updated the readme. Good catch on describing the things.

2023-02-23 19:02 UTC, cbron approved these changes

2023-02-27 18:15 UTC, rmweir approved these changes

2023-02-27 18:20 UTC, merged