Add unit tests and comments to the name package
rancher/wrangler pull request #424
Opened 2024-04-29 20:48 UTC by JonCrowther

Just some minor tech debt. Add comments to each of the exported functions. A lot of these functions are not great (would prefer to return errors), but since they're exported we should at minimum provide comments.

I added some unit tests to `SafeConcatName` because I've used it extensively elsewhere so I want to make sure it doesn't get broken accidentally.

2024-04-30 14:14 UTC, maxsokolovsky requested changes

2024-04-30 14:14 UTC, maxsokolovsky commented on pkg/name/name_test.go
> +			output: string64encoded,
Nit: you could just inline the output with a string literal.

2024-04-30 14:14 UTC, maxsokolovsky commented on pkg/name/name.go
> +// by cutting the string off at 56 characters and setting the last 5 with an encoded version of the concatenated string.
I think the cutoff is after 57 characters and the other 6 are the hyphen plus the hash.

2024-05-01 14:07 UTC, JonCrowther commented on pkg/name/name.go
> +func Hex(s string, n int) string {
Done

2024-05-01 14:08 UTC, JonCrowther commented on pkg/name/name_test.go
> +func TestSafeConcatName(t *testing.T) {
Done for all the tests

2024-05-01 20:30 UTC, maxsokolovsky approved these changes

2024-05-03 16:28 UTC, tomleb approved these changes

2024-05-10 13:58 UTC, merged