K8s 1.30
rancher/wrangler pull request #425
Opened 2024-04-30 14:19 UTC by tomleb

# Issue

Wrangler relies on `k8s.io/code-generator` for _some_ of its generators. Starting with k8s 1.30, these generators have been migrated,  in a backward incompatible way, from `k8s.io/gengo` to `k8s.io/gengo/v2`. We must adapt the code with the new major version of gengo.

# Changes in `gengo/v2`

One major change in the API is that before, you had to create a [GeneratorArgs](https://github.com/kubernetes/gengo/blob/51d4e06bde7070d095fd4c266e51dbe135511a97/args/args.go#L51). It contained information such as: [InputDirs](https://github.com/kubernetes/gengo/blob/51d4e06bde7070d095fd4c266e51dbe135511a97/args/args.go#L53) to point to directories that need codegen, [OutputBase](https://github.com/kubernetes/gengo/blob/51d4e06bde7070d095fd4c266e51dbe135511a97/args/args.go#L56) to specify a directory tree to write file to, [CustomArgs](https://github.com/kubernetes/gengo/blob/51d4e06bde7070d095fd4c266e51dbe135511a97/args/args.go#L85) for generator-specific information.

This struct is no longer used in `gengo/v2`, and instead is replaced in the following way:
- `InputDirs`: This is now provided in a new argument to the [Execute function](https://github.com/kubernetes/gengo/blob/51d4e06bde7070d095fd4c266e51dbe135511a97/v2/execute.go#L76).

- `OutputBase`: Generators would compute "`output file = <output base>/<package>/...`" to know which directory the generated file needs to be in. By convention, generators now expects an absolute path to the destination directory. For example:
```diff
-	args.OutputPackagePath = filepath.Join(customArgs.Package, "clientset")
+	clientSetArgs.OutputDir = filepath.Join(customArgs.OutputBase, customArgs.Package, "clientset")
```
- `CustomArgs`: Custom args aren't part of the API anymore. If the `Target`/`Generator` needs custom arguments, you must find another way of passing it to it. By convention it's done by having a `GetTarget` function that accepts such an argument, and wrapping it by a function that doesn't accept it. Here's an example:
```diff
-	if err := genericArgs.Execute(
-		clientgenerators.NameSystems(nil),
-		clientgenerators.DefaultNameSystem(),
-		clientGen.Packages,
+	getTargets := func(context *generator.Context) []generator.Target {
+		return clientGen.Packages(context, customArgs)
+	}
```

# Commits

1. DeepCopy generator

Not much changed here. We're now referencing gengo directly instead of [k8s.io/code-generator's newtype](https://github.com/kubernetes/code-generator/blob/release-1.29/cmd/deepcopy-gen/args/args.go#L28) 

2. ClientSet generator

Migrates the clientset generator to gengo/v2.

3. Listers generator

Migrates the listers generator to gengo/v2.

4. Informers generator

Migrates the informers generator to gengo/v2.

5. setGenClient middleware

TODO: More info on this

6.

2024-04-30 19:46 UTC, tomleb commented on pkg/controller-gen/args/args.go
> +	Boilerplate []byte
I'm gonna try to remove this to make it as it was before if possible.

2024-04-30 20:46 UTC, MbolotSuse requested changes
There's one other place that we should update the go version of: https://github.com/rancher/wrangler/blob/2a768fdce92ff55c3f08639708dc11c9cdfa3e4a/.github/workflows/lint.yaml#L4. Would be good to give that a look as well.

2024-05-01 12:11 UTC, tomleb commented on pkg/controller-gen/args/args.go
> +	Boilerplate []byte
As discussed previously, I ended up renaming this to `BoilerplateContent` instead and added a comment.

Ideally, `CustomArgs` would be private and wouldn't embed `Options`, but that's not the case yet :shrug:

2024-05-01 12:15 UTC, tomleb commented
Recent changes:
- Rebased from latest wrangler master
- Pulled in latest lasso with k8s 1.30 support
- Renamed `Boilerplate` to `BoilerplateContent`
- Updated the Go version in the linting script

2024-05-01 16:53 UTC, MbolotSuse reviewed
Two comments on how we are structuring the package path.

2024-05-01 18:21 UTC, galal-hussein approved these changes
LGTM

2024-05-01 18:55 UTC, MbolotSuse commented on pkg/controller-gen/main.go
> +	clientSetArgs.OutputPkg = filepath.Join(customArgs.Package, "clientset")
Resolving, the imports seem to be backward compatible since we move the generated after they have been made.

2024-05-01 19:11 UTC, MbolotSuse approved these changes

2024-05-01 20:16 UTC, merged